Flockbuster/Pages/Admin/Create/Movie.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Flockbuster.Service.Methods;

namespace Flockbuster.Pages.Admin.Create
{
    public class MovieModel : PageModel
    {
        private readonly IMovie _movie;

        public MovieModel(IMovie movie)
        {
            _movie = movie;
        }
        [BindProperty]
        public Movies Movie { get; set; } = new Movies();

        [BindProperty]
        public List<Genre> Genres { get; set; } = new List<Genre>();

        [BindProperty]
        public string Title { get; set; } = string.Empty;

        [BindProperty]
        public int AgeRating { get; set; }

        [BindProperty, DisplayName("Movie Picture")]
        public IFormFile Img { get; set; }
        [BindProperty]
        public int Hours { get; set; }

        [BindProperty]
        public int Miuntes { get; set; }

        [BindProperty]
        public DateTime ReleaseDate { get; set; }

        [BindProperty]
        public int GenreId { get; set; }

        [BindProperty]
        public int Price { get; set; }

        [BindProperty]
        public string AdminPassword { get; set; } = string.Empty;
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                Genres = _movie.GetGenres();
                return Page();
            }
        }
        public IActionResult OnPostCancel() => RedirectToPage("/Admin/Movies");
        public IActionResult OnPostCreate()
        {
            if (AdminPassword != "Admin1234!" || ReleaseDate <= DateTime.MinValue || ReleaseDate >= DateTime.MaxValue || ReleaseDate >= DateTime.Now.Date || Title == null || Hours == 0 || Price < 0 || GenreId == 0) { return RedirectToPage("/Admin/Create/Movie"); }

            _movie.CreateMovie(Title, AgeRating, Hours, Miuntes, ReleaseDate, Price, GenreId);

            if (Img != null && Img.Length > 0)
            {
                int id = _movie.GetMovieByTitle(Title);
                string uniqueFileName = $"id{id}{Path.GetExtension(Img.FileName)}";
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pics", "Movies", uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create)) { Img.CopyTo(fileStream); }

                string relativeFilePath = $"/pics/Movies/{uniqueFileName}";
                _movie.UpdateMoviePicture(id, relativeFilePath);
            }

            return RedirectToPage("/Admin/Movies");
        }
    }
}

Flockbuster/Pages/Admin/Edit/Movie.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Flockbuster.Service.Methods;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages.Admin.Edit
{
    public class MovieModel : PageModel
    {
        private readonly IMovie _movie;

        public MovieModel(IMovie movie)
        {
            _movie = movie;
        }
        [BindProperty]
        public Movies Movie { get; set; } = new Movies();

        [BindProperty]
        public string Title { get; set; } = string.Empty;

        [BindProperty]
        public int AgeRating { get; set; } 

        [BindProperty, DisplayName("Movie Picture")]
        public IFormFile Img { get; set; }
        [BindProperty]
        public int Hours { get; set; } 

        [BindProperty]
        public int Miuntes { get; set; } 

        [BindProperty, DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }

        [BindProperty]
        public int Price { get; set; } 

        [BindProperty]
        public string AdminPassword { get; set; } = string.Empty;
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                int? tempid = HttpContext.Session.GetInt32("TempMovieID");
                int id = tempid.HasValue ? tempid.Value : 0;
                Movie = _movie.GetMoviesById(id);

                ReleaseDate = Movie.RelaseDate;

                return Page();
            }
        }
        public IActionResult OnPostCancel()
        {
            HttpContext.Session.Remove("TempMovieId");
            return RedirectToPage("/Admin/Movies");
        }
        public IActionResult OnPostUpdate()
        {
            if (AdminPassword == "Admin1234!")
            {
                int? tempid = HttpContext.Session.GetInt32("TempMovieID");
                int id = tempid.HasValue ? tempid.Value : 0;

                _movie.UpdateMovie(id, Title, AgeRating, Hours, Miuntes, ReleaseDate, Price);

                if (Img != null && Img.Length > 0)
                {
                                        
                    string uniqueFileName = $"id{id}{Path.GetExtension(Img.FileName)}";
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pics", "Movies", uniqueFileName);

                    if (Movie.Img == filePath)
                    {
                        Directory.Delete(filePath);
                    }

                    using (var fileStream = new FileStream(filePath, FileMode.Create)) { Img.CopyTo(fileStream); }

                    string relativeFilePath = $"/pics/Movies/{uniqueFileName}";
                    _movie.UpdateMoviePicture(id, relativeFilePath);
                }

                HttpContext.Session.Remove("TempMovieID");
                return RedirectToPage("/Admin/Movies");
            }
            else
            {
                HttpContext.Session.Remove("TempMovieID");
                return RedirectToPage("/Admin/Movies");
            }
        }
    }
}

Flockbuster/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty]
        public string FullName { get; set; } = string.Empty;

        [BindProperty]
        public string Email { get; set; } = string.Empty;

        [BindProperty]
        public string Subject { get; set; } = string.Empty;

        [BindProperty, MaxLength(500)]
        public string Textarea { get; set; } = string.Empty;

        public void OnGet()
        {
        }
        public IActionResult OnPostContact()
        {
            Console.WriteLine($"Fullname: {FullName}\nEmail: {Email}\nSubject: {Subject}\n\n{Textarea}");
            return RedirectToPage("/Contact");
        }
    }
}

Flockbuster/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Flockbuster.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Flockbuster/Pages/Index.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Flockbuster.Service.Methods;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
		private readonly IMovie _movie;
        private readonly IUser _user;

		public IndexModel(ILogger<IndexModel> logger, IMovie movie, IUser user)
		{
            _logger = logger;
			_movie = movie;
            _user = user;
		}

		[BindProperty]
		public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
        [BindProperty]
        public List<Movies> ThreeNewestMovies { get; set; } = new List<Movies>();
        public void OnGet()
        {
            List<Movies> templist = new List<Movies>();
            ListOfMovies = _movie.GetMovies();
            templist = ListOfMovies.ToList();
            templist.Reverse();
            ThreeNewestMovies = templist.Take(3).ToList();
        }
        public IActionResult OnPostBorrow(int movieId)
        {
            int? tempid = HttpContext.Session.GetInt32("ID");
            int id = tempid.HasValue ? tempid.Value : 0;

            int balance = _user.GetUsersById(id).Balance;
            int price = _movie.GetMoviesById(movieId).Price;

            if (balance >= price)
            {
                _movie.BorrowMovie(movieId, id);
                _user.UpdateUserBalanceMinus(id, price);
                return RedirectToPage("/user/dashboard");
            }
            else
            {
                ModelState.AddModelError("Funds", "No funds");
                return RedirectToPage("/user/dashboard");
            }
        }
    }
}

Flockbuster/Pages/Movies.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages
{
    public class MoviesModel : PageModel
    {
        private readonly IMovie _movie;
        private readonly IUser _user;
        public MoviesModel(IMovie movie, IUser user)
        {
            _movie = movie;
            _user = user;
        }
        [BindProperty]
        public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
        public void OnGet()
        {
            ListOfMovies = _movie.GetMovies();
            foreach (Movies mov in ListOfMovies)
            {
                List<Genre> genreForMovies = _movie.GetMovieGenre(mov.Id);
                mov.Genres = genreForMovies;
            }
        }
        public IActionResult OnPostBorrow(int movieId)
        {
            int? tempid = HttpContext.Session.GetInt32("ID");
            int id = tempid.HasValue ? tempid.Value : 0;

            int balance = _user.GetUsersById(id).Balance;
            int price = _movie.GetMoviesById(movieId).Price;

            if (balance >= price)
            {
                _movie.BorrowMovie(movieId, id);
                _user.UpdateUserBalanceMinus(id, price);
                return RedirectToPage("/User/Dashboard");
            }
            else
            {
                ModelState.AddModelError("Funds", "No funds");
                return RedirectToPage("/Movies");
            }
        }
    }
}

Flockbuster/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Flockbuster/Pages/Signin.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages
{
    public class SigninModel : PageModel
    {
        private readonly IUser _user;
        public SigninModel(IUser user)
        {
            _user = user;
        }

        public void OnGet()
        {
        }
        [BindProperty, Required]
        public string Mail { get; set; } = string.Empty;
        [BindProperty, Required]
        public string Password { get; set; } = string.Empty;
        public IActionResult OnPost()
        {
            Users user = new Users();
            user.Email = Mail;

            if (string.IsNullOrWhiteSpace(Password)) { ModelState.AddModelError("asp", "Wrong password"); }
            else { user = _user.GetUserDetailsLogin(user.Email, Password); }

            if (string.IsNullOrEmpty(user.Name)) { ModelState.AddModelError("asp", "Wrong password or email"); }

            if (ModelState.IsValid)
            {
                HttpContext.Session.Boolean("Admin", user.IsAdmin);
                HttpContext.Session.SetString("Name", user.Name);
                HttpContext.Session.SetInt32("ID", user.Id);
                if (user.IsAdmin == true) { return RedirectToPage("/Admin/Dashboard"); }
                else { return RedirectToPage("/user/dashboard"); }
            }
            else { return Page(); }
        }
    }
}

Flockbuster/Pages/Signout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages
{
    public class SignoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue)
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPostDontSignOut()
        {
            if (HttpContext.Session.GetBoolean("Admin") == false) { return RedirectToPage("/User/dashboard"); }
            else { return RedirectToPage("/Admin/Dashboard"); }
        }
        public IActionResult OnPostSignOut()
        {
            HttpContext.Session.Remove("Admin");
            HttpContext.Session.Remove("Name");
            HttpContext.Session.Remove("ID");
            return RedirectToPage("/Index");
        }
    }
}

Flockbuster/Pages/Signup.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages
{
    public class SignupModel : PageModel
    {
        private readonly IUser _user;

        public SignupModel(IUser user)
        {
            _user = user;
        }

        [BindProperty, Required]
        public string FirstName { get; set; } = string.Empty;

        [BindProperty, Required]
        public string LastName { get; set; } = string.Empty;

        [BindProperty, Required]
        public string EmailAddress { get; set; } = string.Empty;

        [BindProperty, Required]
        public string Age { get; set; } = string.Empty;

        [BindProperty, Required]
        [MinLength(8)]
        public string Password { get; set; } = string.Empty;

        [BindProperty, Required]
        [Compare(nameof(Password), ErrorMessage = "Make sure passwords are matching")]
        public string ConfirmPassword { get; set; } = string.Empty;

        public IActionResult OnPost()
        {
            string fullName = FirstName + " " + LastName;

            if (!string.IsNullOrWhiteSpace(EmailAddress))
            {
                _user.CreateUser(fullName, Convert.ToInt32(Age), EmailAddress, ConfirmPassword);
                Users user = new Users();

                user.Email = EmailAddress;
                user = _user.GetUserByMail(user.Email);

                HttpContext.Session.Boolean("Admin", user.IsAdmin);
                HttpContext.Session.SetString("Name", user.Name);
                HttpContext.Session.SetInt32("ID", user.Id);
                if (user.IsAdmin) { return RedirectToPage("/admin/dashboard"); }
                else { return RedirectToPage("/user/dashboard"); }
            }

            else
            {
                ModelState.AddModelError("Signup", "Details don't look right");
                return Page();
            }

        }
    }
}

Flockbuster/Pages/Contact.cshtml
@page
@model Flockbuster.Pages.ContactModel
@{
    ViewData["Title"] = "Contact page";
}

<div class="d-flex justify-content-around">
    <div class="card h-100 col-sm-3 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body d-flex justify-content-center">
            <img class="h-50 col-xl-5 col-lg-5 col-md-5 col-sm-5 col-5 rounded-circle" src="/pics/flockbuster.png" />
		</div>
        <div class="container text-center mt-4">
            <p>
                Email: sanitiw514@gmail.com<br />
                Phone number: +45 99 19 93 64<br />
                Address: Middle of, 9999 Nowhere
            </p>
        </div>
	</div>
    <div class="card h-100 col-md-6 col-sm-6 col-6 w-50 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <h6 class="mb-3 text-primary">Contact us</h6>
            </div>
            <form method="post">
                <div class="form-group">
                    <input type="Text"
                        class="form-control my-3"
                        id="fullNameInput"
                        placeholder="Full name"
                        asp-for="FullName">
                </div>
                <div class="form-group">
                    <input type="Text"
                        class="form-control my-3"
                        id="emailInput"
                        placeholder="Email"
                        asp-for="Email">
                </div>
                <div class="form-group">
                    <input type="text"
                        class="form-control my-3"
                        id="subjectInput"
                        placeholder="Subject"
                        asp-for="Subject">
                </div>
                <div class="form-group">
                    <textarea data-val="true"
                        data-val-maxlength-max="500"
                        id="Textarea"
                        class="form-control my-3"
                        rows="6" 
                        placeholder="Write something" 
                        asp-for="Textarea">
                    </textarea>
                </div>
                <button type="submit" class="btn btn-outline-primary mt-3 w-100" asp-page-handler="Contact">
                    Contact
                </button>
            </form>
		</div>
	</div>
</div>

Flockbuster/Pages/Index.cshtml
@page
@using Flockbuster.Domain.Models;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="carousel" class="carousel slide carousel-fade mb-3">
    <div class="carousel-inner">
        
        <div class="carousel-item active">
            <img src="/pics/placeholder.png" class="d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="/pics/placeholder.png" class="d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="/pics/placeholder.png" class="d-block w-100">
        </div>

        @*@foreach (Movies mov in Model.ThreeNewestMovies)
        {
            <div class="carousel-item active">
                <img src="@mov.Img" class="d-block w-100">
            </div>
        }
        Look into later
        *@  

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="scrollmenu my-4 border-top">
    @foreach (Movies mov in Model.ListOfMovies)
    {
        <img src="@mov.Img" class="ms-2 mh-18" data-bs-toggle="modal" data-bs-target="#movBorrowModal-@mov.Id" />
    }
</div>


@foreach (Movies mov in Model.ListOfMovies)
{
    <div class="modal fade" id="movBorrowModal-@mov.Id" tabindex="-1" aria-labelledby="movBorrowModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content bg-transparent border-0">
                <div class="d-flex justify-content-center">
                    <img src="@mov.Img" style="height:420px;width:280px;" />
                </div>
                <div class="text-center text-white mt-4">
                    <h6>
                        @mov.Title
                    </h6>
                    <p>
                        Required age: @mov.RequiredAge<br />
                        Release date: @mov.RelaseDate.ToShortDateString()
                    </p>
                </div>
                <div class="d-flex justify-content-center">
                    <button type="button" class="btn btn-danger mt-4 me-2" data-bs-dismiss="modal">Cancel</button>
                    @if (HttpContext.Session.GetInt32("ID") > 1)
                    {
                        <form method="post">
                            <button class="btn btn-warning mt-4 ms-2" type="submit" data-bs-dismiss="modal" asp-page-handler="Borrow" asp-route-movieId="@mov.Id">Borrow for @mov.Price DKK</button>
                        </form>
                    }
                    else
                    {
                        <button class="btn btn-warning mt-4 ms-2" data-bs-dismiss="modal" disabled>Disabled</button>
                    }
                </div>
            </div>
        </div>
    </div>
}

Flockbuster/Pages/Movies.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.MoviesModel
@{
    ViewData["Title"] = "Movies";
}

<div id="movies" class="my-4">
    @foreach (Movies mov in Model.ListOfMovies)
    {
        <img src="@mov.Img" class="ms-2" data-bs-toggle="modal" data-bs-target="#movBorrowModal-@mov.Id" />
    }
</div>


@foreach (Movies mov in Model.ListOfMovies)
{
    <div class="modal fade" id="movBorrowModal-@mov.Id" tabindex="-1" aria-labelledby="movBorrowModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content bg-transparent border-0">
                <div class="d-flex justify-content-center">
                    <img src="@mov.Img" style="height:420px;width:280px;" />
                </div>
                <div class="text-center text-white mt-4">
                    <h6>
                        @mov.Title
                    </h6>
                    <p>
                        Required age: @mov.RequiredAge<br />
                        Release date: @mov.RelaseDate.ToShortDateString()
                    </p>
                </div>
                <div class="d-flex justify-content-center">
                    <button type="button" class="btn btn-danger mt-4 me-2" data-bs-dismiss="modal">Cancel</button>
                    @if (HttpContext.Session.GetInt32("ID") > 1)
                    {
                        <form method="post">
                            <button class="btn btn-warning mt-4 ms-2" type="submit" data-bs-dismiss="modal" asp-page-handler="Borrow" asp-route-movieId="@mov.Id">Borrow for @mov.Price DKK</button>
                        </form>
                    }
                    else
                    {
                        <button class="btn btn-warning mt-4 ms-2" data-bs-dismiss="modal" disabled>Disabled</button>
                    }
                </div>
            </div>
        </div>
    </div>
}

Flockbuster/Pages/Signin.cshtml
@page
@model Flockbuster.Pages.SigninModel
@{
    ViewData["Title"] = "Sign in";
}

<div class="container d-flex justify-content-center text-center postition-relative">
    <div class="col-sm-2 position-absolute top-50 start-50 translate-middle">
        <div class="col shadow-lg p-3 mb-5 bg-body-tertiary rounded">
            <h1 class="h3 mb-2 fw-normal">Sign in</h1>
            <form method="post"
                  id="SignInPage">
                <div class="form-floating my-2">
                    <input type="email"
                           class="form-control"
                           id="eMailInput"
                           placeholder="Email address"
                           asp-for="Mail">
                    <label for="eMailInput">Email address</label>
                </div>
                <div class="form-floating my-2">
                    <input type="password"
                           class="form-control"
                           id="passwordInput"
                           placeholder="password"
                           asp-for="Password">
                    <label for="passwordInput">Password</label>
                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
                <button type="submit" class="btn btn-primary btn-group" onclick="PopToast('Wrong email or password')">
                    Sign in
                </button>
            </form>
            <p>Not a user yet? Sign up by clicking <a href="/signup">here</a></p>
        </div>
    </div>
</div>

@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

Flockbuster/Pages/Signout.cshtml
@page
@model Flockbuster.Pages.SignoutModel
@{
    ViewData["Title"] = "Sign out";
}

<div class="container d-flex justify-content-center text-center postition-relative">
    <div class="col-sm-2 position-absolute top-50 start-50 translate-middle">
        <div class="col shadow-lg p-3 mb-5 bg-body-tertiary rounded">
            <h1 class="h3 mb-2 fw-normal">Logout</h1>
            <p>Are you sure you wanna logout?</p>
            <form method="post">
                <button type="submit" class="btn btn-success mx-1 w-25" asp-page-handler="SignOut">
                    Yes
                </button>
                <button type="submit" class="btn btn-danger mx-1 w-25" asp-page-handler="DontSignOut">
                    No
                </button>
            </form>
        </div>
    </div>
</div>

Flockbuster/Pages/Signup.cshtml
@page
@model Flockbuster.Pages.SignupModel
@{
    ViewData["Title"] = "Sign up";
}

<div class="container d-flex justify-content-center text-center postition-relative">
    <div class="col-sm-2 position-absolute top-50 start-50 translate-middle">
        <div class="col shadow-lg p-3 mb-5 bg-body-tertiary rounded">
            <h1 class="h3 mb-2 fw-normal">Welcome!</h1>
            <p>Feel free to sign up</p>
            <form class="d-grid"
                  method="post"
                  id="SignInPage">
                <div class="form-floating mb-2">
                    <input type="Text"
                           class="form-control"
                           id="firstNameInput"
                           placeholder="First name"
                           asp-for="FirstName">
                    <label for="firstNameInput">First name</label>
                </div>
                <div class="form-floating mb-2">
                    <input type="Text"
                           class="form-control"
                           id="lastNameInput"
                           placeholder="Last name"
                           asp-for="LastName">
                    <label for="lastNameInput">Last name</label>
                </div>
                <div class="form-floating mb-2">
                    <input type="email"
                           class="form-control"
                           id="emailAddressInput"
                           placeholder="name@example.com"
                           asp-for="EmailAddress">
                    <label for="emailAddressInput">Email address</label>
                </div>
                <div class="form-floating mb-2">
                    <input type="number"
                           class="form-control"
                           id="ageInput"
                           placeholder="Age"
                           asp-for="Age">
                    <label for="ageInput">Age</label>
                </div>
                <div class="form-group">
                    <div class="form-floating mb-2">
                        <input type="password"
                               class="form-control"
                               id="passwordInput"
                               placeholder="Password"
                               asp-for="Password">
                        <label for="passwordInput">Password</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-floating mb-4">
                        <input type="password"
                               class="form-control"
                               id="confirmPasswordInput"
                               placeholder="Confirm password"
                               asp-for="ConfirmPassword">
                        <label for="confirmPasswordInput">Confirm password</label>
                        <div asp-validation-summary="All" class="text-danger"></div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">
                    Sign up
                </button>
            </form>
            <p>Already a user? Sign in by clicking <a href="/Signin">here</a></p>
        </div>
    </div>
</div>

@section scripts{
    <partial name="_ValidationScriptsPartial" />
}