Flockbuster/Pages/Admin/Dashboard.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using static System.Reflection.Metadata.BlobBuilder;

namespace Flockbuster.Pages.Admin
{
    public class DashboardModel : PageModel
    {
		private readonly IUser _user;
		private readonly IMovie _movie;

		public DashboardModel(IUser user, IMovie movie)
		{
			_user = user;
			_movie = movie;
		}
		[BindProperty]
		public List<BorrowedMovie> ListOfBorrowedMovies { get; set; } = new List<BorrowedMovie>();
		[BindProperty]
		public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
		[BindProperty]
		public List<Users> ListOfUsers { get; set; } = new List<Users>();
		[BindProperty]
		public List<Genre> ListOfGenres { get; set; } = new List<Genre>();

		public IActionResult OnGet()
		{
			ListOfUsers = _user.GetUsers();
			ListOfUsers.RemoveAt(0);
			ListOfMovies = _movie.GetMovies();
			ListOfBorrowedMovies = _movie.GetBorrowedMovies();
			ListOfGenres = _movie.GetGenres();
			if (!HttpContext.Session.GetBoolean("Admin"))
			{
				return RedirectToPage("/error/403");
			}
			else
			{
				return Page();
			}

		}
	}
}

Flockbuster/Pages/Admin/Edit/user.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages.Admin.Edit
{
    public class UserModel : PageModel
    {
        private readonly IUser _user;
        public UserModel(IUser user)
        {
            _user = user;
        }

        [BindProperty]
        public Users User { get; set; } = new Users();

        [BindProperty]
        public string UserFirstName { get; set; } = string.Empty;

        [BindProperty]
        public string UserLastName { get; set; } = string.Empty;

        [BindProperty]
        public string FirstName { get; set; } = string.Empty;

        [BindProperty]
        public string LastName { get; set; } = string.Empty;

        [BindProperty]
        public string EmailAddress { get; set; } = string.Empty;

        [BindProperty]
        public string Age { get; set; } = string.Empty;

        [BindProperty]
        [MinLength(8)]
        public string Password { get; set; } = string.Empty;

        [BindProperty]
        public string ConfirmPassword { get; set; } = string.Empty;
        [BindProperty]
        public string AdminPassword { get; set; } = string.Empty;
        [BindProperty]
        public bool IsChecked { get; set; }

        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                int? tempid = HttpContext.Session.GetInt32("TempUserId");
                int id = tempid.HasValue ? tempid.Value : 0;
                User = _user.GetUsersById(id);

                string[] names = User.Name.Split(' ');
                UserFirstName = names[0];
                UserLastName = names[1];

                return Page();
            }
        }

        public IActionResult OnPostCancel()
        {
            HttpContext.Session.Remove("TempUserId");
            return RedirectToPage("/Admin/Users");
        }
        public IActionResult OnPostUpdate()
        {
            int? tempid = HttpContext.Session.GetInt32("TempUserId");
            int id = tempid.HasValue ? tempid.Value : 0;
            string fullName = FirstName + " " + LastName;
            if (AdminPassword == "Admin1234!")
            {
                if (!string.IsNullOrEmpty(Password) && Password == ConfirmPassword) { _user.UpdateUserPassword(id, ConfirmPassword); }
                if (IsChecked) { _user.Admin(id, true); }
                else { _user.Admin(id, false); }
                _user.UpdateUser(id, fullName, Convert.ToInt32(Age), EmailAddress);
                HttpContext.Session.Remove("TempUserId");
                return RedirectToPage("/Admin/Users");
            }
            else { return RedirectToAction("adminInput"); }
        }
    }
}

Flockbuster/Pages/Admin/MovieHistory.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages.Admin
{
    public class MovieHistoryModel : PageModel
    {
        private readonly IMovie _movie;
        private readonly IUser _user;

        public MovieHistoryModel(IMovie movie, IUser user)
        {
            _movie = movie;
            _user = user;
        }
        [BindProperty]
        public List<BorrowedMovie> BorrowedMovies { get; set; } = new List<BorrowedMovie>();
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                BorrowedMovies = _movie.GetBorrowedMovies();

                foreach (BorrowedMovie borrowed in BorrowedMovies)
                {
                    borrowed.MovieName = _movie.GetMoviesById(borrowed.MovieID).Title;
                    borrowed.UserName = _user.GetUsersById(borrowed.UserID).Name;
                }

                return Page();
            }
        }
    }
}

Flockbuster/Pages/Admin/Users.cshtml.cs
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Flockbuster.Domain.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Flockbuster.Service.Methods;

namespace Flockbuster.Pages.Admin
{
    public class UsersModel : PageModel
    {
        private readonly IUser _user;
        public UsersModel(IUser user)
        {
            _user = user;
        }
        [BindProperty]
        public List<Users> ListOfUsers { get; set; } = new List<Users>();
        public IActionResult OnGet()
        {
            ListOfUsers = _user.GetUsers();
            ListOfUsers.RemoveAt(0);

            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPostEdit(int userId)
        {
            HttpContext.Session.SetInt32("TempUserId", userId);
            return RedirectToPage("/Admin/Edit/User");
        }
        public IActionResult OnPostDelete(int userId)
        {
            _user.DeleteUser(userId);
            return RedirectToPage("/Admin/Users");
        }
    }
}

Flockbuster/Pages/User/Dashboard.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using static System.Reflection.Metadata.BlobBuilder;

namespace Flockbuster.Pages.User
{
    public class DashboardModel : PageModel
    {
		private readonly IUser _user;
		private readonly IMovie _movie;

		public DashboardModel(IUser user, IMovie movie)
		{
			_user = user;
			_movie = movie;
		}
		[BindProperty]
		public Users UserDetails { get; set; }
		[BindProperty]
		public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
		[BindProperty]
		public int Balance { get; set; }
		public IActionResult OnGet()
		{
			if (!HttpContext.Session.GetInt32("ID").HasValue || HttpContext.Session.GetBoolean("Admin"))
			{
				return RedirectToPage("/error/403");
			}
			else
			{
				int? tempId = HttpContext.Session.GetInt32("ID");
				int id = tempId.HasValue ? tempId.Value : 0;
				UserDetails = _user.GetUsersById(id);

				BorrowedMovie loanedMovie = new BorrowedMovie();
				loanedMovie = _movie.GetBorrowedMovieById(id);

				Movies borrowedMovie = new Movies();
				borrowedMovie = _movie.GetMoviesById(loanedMovie.MovieID);
				borrowedMovie.ReturnDate = loanedMovie.ReturnDate;

				if (loanedMovie.Id != 0 && loanedMovie.IsBorrowed)
				{
					ListOfMovies.Add(borrowedMovie);
				}
				foreach (Movies mov in ListOfMovies)
				{
					List<Genre> genresForMovie = _movie.GetMovieGenre(loanedMovie.MovieID);
					mov.Genres = genresForMovie;
				}

				return Page();
			}
		}
		public IActionResult OnPostReturn(int movieId)
		{
            int? tempId = HttpContext.Session.GetInt32("ID");
            int id = tempId.HasValue ? tempId.Value : 0;
            _movie.ReturnMovie(movieId, id);
			return RedirectToPage("/User/Dashboard");
		}
		public IActionResult OnPostAddBalance()
		{
			int? tempId = HttpContext.Session.GetInt32("ID");
			int id = tempId.HasValue ? tempId.Value : 0;
			if (Balance > 0) 
			{
				_user.UpdateUserBalancePlus(id, Balance);
			}
			else
			{
                Console.WriteLine(Balance);
            }
			return RedirectToPage("/User/Dashboard");
		}
		public IActionResult OnPostWithdrawBalance()
		{
			int? tempId = HttpContext.Session.GetInt32("ID");
			int id = tempId.HasValue ? tempId.Value : 0;
			if (Balance > 0 && Balance <= _user.GetUsersById(id).Balance)
			{
				_user.UpdateUserBalanceMinus(id, Balance);
			}
			else
			{
				Console.WriteLine(Balance);
			}
			return RedirectToPage("/User/Dashboard");
		}
	}
}

Flockbuster/Pages/User/MovieHistory.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static System.Reflection.Metadata.BlobBuilder;

namespace Flockbuster.Pages.User
{
    public class MovieHistoryModel : PageModel
    {
		private readonly IUser _user;
		private readonly IMovie _movie;

		public MovieHistoryModel(IUser user, IMovie movie)
		{
			_user = user;
			_movie = movie;
		}
		[BindProperty]
		public Users UserDetails { get; set; }
		[BindProperty]
		public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
		public IActionResult OnGet()
		{
			if (!HttpContext.Session.GetInt32("ID").HasValue || HttpContext.Session.GetBoolean("Admin"))
			{
				return RedirectToPage("/error/403");
			}
			else
			{
				int? tempId = HttpContext.Session.GetInt32("ID");
				int id = tempId.HasValue ? tempId.Value : 0;
				UserDetails = _user.GetUsersById(id);

				BorrowedMovie loanedMovie = new BorrowedMovie();
				loanedMovie = _movie.GetBorrowedMovieById(id);

				Movies borrowedMovie = new Movies();
				borrowedMovie = _movie.GetMoviesById(loanedMovie.MovieID);

				if (loanedMovie.Id != 0 && loanedMovie.WasBorrowed)
				{
					ListOfMovies.Add(borrowedMovie);
				}
				foreach (Movies mov in ListOfMovies)
				{
					List<Genre> genresForMovie = _movie.GetMovieGenre(loanedMovie.MovieID);
					mov.Genres = genresForMovie;
				}

				return Page();
			}
		}
	}
}

Flockbuster/Pages/User/Movies.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages.User
{
    public class MoviesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Flockbuster/Pages/User/Settings.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Flockbuster.Service.Methods;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using static System.Reflection.Metadata.BlobBuilder;

namespace Flockbuster.Pages.User
{
    public class SettingsModel : PageModel
    {
        private readonly IUser _user;

        public SettingsModel(IUser user)
        {
            _user = user;
        }
        [BindProperty]
        public Users User { get; set; } = new Users();
        
        [BindProperty]
        public string UserFirstName { get; set; } = string.Empty;

        [BindProperty]
        public string UserLastName { get; set; } = string.Empty;

        [BindProperty, DisplayName("Profile Picture")]
        public IFormFile Img { get ; set; }
        [BindProperty]
        public string FirstName { get; set; } = string.Empty;

        [BindProperty]
        public string LastName { get; set; } = string.Empty;

        [BindProperty]
        public string EmailAddress { get; set; } = string.Empty;

        [BindProperty]
        public string Age { get; set; } = string.Empty;

        [BindProperty]
        [MinLength(8)]
        public string Password { get; set; } = string.Empty;

        [BindProperty]
        public string ConfirmPassword { get; set; } = string.Empty;
        [BindProperty]
        [Required]
        public string CurrentPassword { get; set; } = string.Empty;

        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                int? tempId = HttpContext.Session.GetInt32("ID");
                int id = tempId.HasValue ? tempId.Value : 0;
                User = _user.GetUsersById(id);

                string[] names = User.Name.Split(' ');
                UserFirstName = names[0];
                UserLastName = names[1];

                return Page();
            }
        }

        public IActionResult OnPostCancel() => RedirectToPage("/User/Dashboard");
        public IActionResult OnPostUpdate()
        {
            int? tempId = HttpContext.Session.GetInt32("ID");
            int id = tempId.HasValue ? tempId.Value : 0;
            string fullName = FirstName + " " + LastName;
            bool currentPassword = _user.CheckPassowrd(id, CurrentPassword);

            if (!currentPassword)
            {
                ModelState.AddModelError("password", "Not the correct password");
                return RedirectToPage("/User/Settings");
            }
            else
            {
                if (!string.IsNullOrEmpty(Password) && Password == ConfirmPassword)
                {
                    _user.UpdateUserPassword(id, Password);
                }
                if (Img != null && Img.Length > 0)
                {
                    string uniqueFileName = $"id{id}{Path.GetExtension(Img.FileName)}";
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pics", "Users", uniqueFileName);

                    if (User.Img == filePath)
                    {
                        Directory.Delete(filePath);
                    }

                    using (var fileStream = new FileStream(filePath, FileMode.Create)) { Img.CopyTo(fileStream); }

                    string relativeFilePath = $"/pics/users/{uniqueFileName}";
                    _user.UpdateUserPicture(id, relativeFilePath);
                }
                _user.UpdateUser(id, fullName, Convert.ToInt32(Age), EmailAddress);
                HttpContext.Session.SetString("Name", fullName);
                return RedirectToPage("/User/Dashboard");
            }
        }
        public IActionResult OnPostDelete()
        {
            int? tempId = HttpContext.Session.GetInt32("ID");
            int id = tempId.HasValue ? tempId.Value : 0;
            bool currentPassword = _user.CheckPassowrd(id, CurrentPassword);

            if (currentPassword)
            {
                HttpContext.Session.Remove("Admin");
                HttpContext.Session.Remove("Name");
                HttpContext.Session.Remove("ID");
                _user.DeleteUser(id);
                return RedirectToPage("/index");
            }
            else
            {
                return Page();
            }
        }
    }
}

Flockbuster/Pages/User/Dashboard.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.User.DashboardModel
@{
    ViewData["Title"] = "Dashboard";
}
<div class="container d-flex justify-content-between">
	<div class="card h-25 col-sm-3 shadow p-2 mb-5 bg-body-tertiary rounded-circle">
		<img class="rounded-circle" src="@Model.UserDetails.Img" />
	</div>
	<div class="card h-100 w-50 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body">
			<div class="row gutters">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
					<h5 class="mb-4">User Details</h5>

				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">User number:</h6>
					@(Model.UserDetails.Id - 1)
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">Name:</h6>
					@Model.UserDetails.Name
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">E-mail:</h6>
					@Model.UserDetails.Email
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">Balance:</h6>
					@Model.UserDetails.Balance DKK 
					<button class="btn btn-outline-success ms-2" data-bs-toggle="modal" data-bs-target="#userBalance"><i class="fa-solid fa-wallet"></i></button>
					@*<a onclick="PopToast('Test design')">Design</a>*@
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="card h-75 w-100 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body">
			@if (Model.ListOfMovies.Count != 0)
			{
				<table class="table">
					<thead>
						<tr>
							<th scope="col">Title</th>
							<th scope="col">Age rating</th>
							<th scope="col">Time to watch</th>
							<th scope="col">Release date</th>
							<th scope="col">Price</th>
							<th scope="col">Return date</th>
							<th scope="col">Genre</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						@foreach (Movies movie in Model.ListOfMovies)
						{
							<tr>
								<td scope="row">@movie.Title</td>
								<td>@movie.RequiredAge</td>
								<td>@(movie.TTW / 3600)h @((movie.TTW / 60) - (movie.TTW / 3600 * 60))m</td>
								<td>@movie.RelaseDate.ToShortDateString()</td>
								<td>@movie.Price DKK</td>
								<td>@movie.ReturnDate.ToShortDateString()</td>
								<td class="dropdown">
									<a class="dropdown-toggle text-dark" role="button" data-bs-toggle="dropdown" aria-expanded="false">
										Genres
									</a>
									<ul class="dropdown-menu" data-bs-auto-close="false">
										@foreach (Genre genre in movie.Genres)
										{
											<li><a class="dropdown-item">@genre.GenreName</a></li>
										}
									</ul>
								</td>
								<td class="d-flex justify-content-end">
									<form method="post">
										<button class="btn btn-outline-danger me-2" type="submit" asp-page-handler="Return" asp-route-movieId="@movie.Id"><i class="fa-solid fa-arrow-right"></i></button>
									</form>
								</td>
							</tr>
						}
					</tbody>
				</table>
			}
			else
			{
				<div class="d-flex justify-content-center">
					<h4>No movies borrowed, check your <a href="~/User/MovieHistory">Movie History</a> for previous borrowed movies</h4>
				</div>
			}
		</div>
	</div>
</div>

<div class="modal fade" id="userBalance" tabindex="-1" aria-labelledby="userBalance" aria-hidden="true">
	<div class="modal-dialog">
		<form method="post">
			<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5 text-success" id="userBalance">Balance</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<label for="Balance">Balance to withdraw or insert</label>
				<input type="number" id="Balance" class="form-control" asp-for="Balance">
			</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success w-25" data-bs-dismiss="modal" asp-page-handler="WithdrawBalance">Withdraw Balance</button>
					<button type="submit" class="btn btn-success w-25" data-bs-dismiss="modal" asp-page-handler="AddBalance">Insert Balance</button>
				</div>
			</div>
		</form>
	</div>
</div>

Flockbuster/Pages/User/MovieHistory.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.User.MovieHistoryModel
@{
    ViewData["Title"] = "Movie History";
}

@if (Model.ListOfMovies.Count() != 0)
{
    <div class="mt-2 container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Age Rating</th>
                    <th scope="col">Time To Watch</th>
                    <th scope="col">Release date</th>
                    <th scope="col">Price</th>
                    <th scope="col">Genres</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Movies mov in Model.ListOfMovies)
                {
                    <tr>
                        <th scope="row">@mov.Id</th>
                        <td>@mov.Title</td>
                        <td>@mov.RequiredAge</td>
                        <td>@(mov.TTW / 3600)h @((mov.TTW / 60) - (mov.TTW / 3600 * 60))m</td>
                        <td>@mov.RelaseDate.ToShortDateString()</td>
                        <td>@mov.Price DKK</td>
                        <td class="dropdown">
                            <a class="dropdown-toggle text-dark" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Genres
                            </a>
                            <ul class="dropdown-menu" data-bs-auto-close="false">
                                @foreach (Genre genre in mov.Genres)
                                {
                                    <li><a class="dropdown-item">@genre.GenreName</a></li>
                                }
                            </ul>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="d-flex justify-content-center text-center postition-relative position-absolute top-50 start-50 translate-middle">
        <h4>No movies was borrowed, borrow one from <a href="~/Movies">Movies</a></h4>
    </div>
}

Flockbuster/Pages/User/Settings.cshtml
@page
@model Flockbuster.Pages.User.SettingsModel
@{
    ViewData["Title"] = "Settings";
}

<div class="container">
    <div class="row gutters">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card h-100">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h6 class="mb-2 text-primary">Personal Details</h6>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="firstNameInput">First name</label>
                                    <input type="Text"
                                           class="form-control"
                                           id="firstNameInput"
                                           value="@Model.UserFirstName"
                                           asp-for="FirstName">
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="lastNameInput">Last name</label>
                                    <input type="Text"
                                           class="form-control"
                                           id="lastNameInput"
                                           value="@Model.UserLastName"
                                           asp-for="LastName">
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="emailAddressInput">Email address</label>
                                    <input type="email"
                                           class="form-control"
                                           id="emailAddressInput"
                                           value="@Model.User.Email"
                                           asp-for="EmailAddress">
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="ageInput">Age</label>
                                    <input type="number"
                                           class="form-control"
                                           id="ageInput"
                                           value="@Model.User.Age"
                                           asp-for="Age">
                                </div>
                            </div>
                        </div>
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h6 class="mt-3 mb-2 text-primary">New Password</h6>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="passwordInput">Password</label>
                                    <input type="password"
                                           class="form-control"
                                           id="passwordInput"
                                           placeholder="Password"
                                           asp-for="Password">
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="confirmPasswordInput">Confirm password</label>
                                    <input type="password"
                                           class="form-control"
                                           id="confirmPasswordInput"
                                           placeholder="Confirm password"
                                           asp-for="ConfirmPassword">
                                </div>
                            </div>
                        </div>
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h6 class="mt-3 mb-2 text-primary">Current password</h6>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="passwordInput">Password</label>
                                    <input type="password"
                                           class="form-control"
                                           id="currentPasswordInput"
                                           placeholder="Password"
                                           asp-for="CurrentPassword">
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label asp-for="Img" class="control-label"></label>
                                    <input asp-for="Img" type="file" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3" asp-page-handler="Update">
                            Update
                        </button>
                        <button type="submit" class="btn btn-secondary mt-3" asp-page-handler="Cancel">
                            Cancel
                        </button>
                        <button type="submit" class="btn btn-danger mt-3" asp-page-handler="Delete">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>