Flockbuster/Pages/Admin/Create/Movie.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Flockbuster.Service.Methods;

namespace Flockbuster.Pages.Admin.Create
{
    public class MovieModel : PageModel
    {
        private readonly IMovie _movie;

        public MovieModel(IMovie movie)
        {
            _movie = movie;
        }
        [BindProperty]
        public Movies Movie { get; set; } = new Movies();

        [BindProperty]
        public List<Genre> Genres { get; set; } = new List<Genre>();

        [BindProperty]
        public string Title { get; set; } = string.Empty;

        [BindProperty]
        public int AgeRating { get; set; }

        [BindProperty, DisplayName("Movie Picture")]
        public IFormFile Img { get; set; }
        [BindProperty]
        public int Hours { get; set; }

        [BindProperty]
        public int Miuntes { get; set; }

        [BindProperty]
        public DateTime ReleaseDate { get; set; }

        [BindProperty]
        public int GenreId { get; set; }

        [BindProperty]
        public int Price { get; set; }

        [BindProperty]
        public string AdminPassword { get; set; } = string.Empty;
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                Genres = _movie.GetGenres();
                return Page();
            }
        }
        public IActionResult OnPostCancel() => RedirectToPage("/Admin/Movies");
        public IActionResult OnPostCreate()
        {
            if (AdminPassword != "Admin1234!" || ReleaseDate <= DateTime.MinValue || ReleaseDate >= DateTime.MaxValue || ReleaseDate >= DateTime.Now.Date || Title == null || Hours == 0 || Price < 0 || GenreId == 0) { return RedirectToPage("/Admin/Create/Movie"); }

            _movie.CreateMovie(Title, AgeRating, Hours, Miuntes, ReleaseDate, Price, GenreId);

            if (Img != null && Img.Length > 0)
            {
                int id = _movie.GetMovieByTitle(Title);
                string uniqueFileName = $"id{id}{Path.GetExtension(Img.FileName)}";
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pics", "Movies", uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create)) { Img.CopyTo(fileStream); }

                string relativeFilePath = $"/pics/Movies/{uniqueFileName}";
                _movie.UpdateMoviePicture(id, relativeFilePath);
            }

            return RedirectToPage("/Admin/Movies");
        }
    }
}

Flockbuster/Pages/Admin/Dashboard.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using static System.Reflection.Metadata.BlobBuilder;

namespace Flockbuster.Pages.Admin
{
    public class DashboardModel : PageModel
    {
		private readonly IUser _user;
		private readonly IMovie _movie;

		public DashboardModel(IUser user, IMovie movie)
		{
			_user = user;
			_movie = movie;
		}
		[BindProperty]
		public List<BorrowedMovie> ListOfBorrowedMovies { get; set; } = new List<BorrowedMovie>();
		[BindProperty]
		public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
		[BindProperty]
		public List<Users> ListOfUsers { get; set; } = new List<Users>();
		[BindProperty]
		public List<Genre> ListOfGenres { get; set; } = new List<Genre>();

		public IActionResult OnGet()
		{
			ListOfUsers = _user.GetUsers();
			ListOfUsers.RemoveAt(0);
			ListOfMovies = _movie.GetMovies();
			ListOfBorrowedMovies = _movie.GetBorrowedMovies();
			ListOfGenres = _movie.GetGenres();
			if (!HttpContext.Session.GetBoolean("Admin"))
			{
				return RedirectToPage("/error/403");
			}
			else
			{
				return Page();
			}

		}
	}
}

Flockbuster/Pages/Admin/Edit/Movie.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Flockbuster.Service.Methods;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages.Admin.Edit
{
    public class MovieModel : PageModel
    {
        private readonly IMovie _movie;

        public MovieModel(IMovie movie)
        {
            _movie = movie;
        }
        [BindProperty]
        public Movies Movie { get; set; } = new Movies();

        [BindProperty]
        public string Title { get; set; } = string.Empty;

        [BindProperty]
        public int AgeRating { get; set; } 

        [BindProperty, DisplayName("Movie Picture")]
        public IFormFile Img { get; set; }
        [BindProperty]
        public int Hours { get; set; } 

        [BindProperty]
        public int Miuntes { get; set; } 

        [BindProperty, DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }

        [BindProperty]
        public int Price { get; set; } 

        [BindProperty]
        public string AdminPassword { get; set; } = string.Empty;
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                int? tempid = HttpContext.Session.GetInt32("TempMovieID");
                int id = tempid.HasValue ? tempid.Value : 0;
                Movie = _movie.GetMoviesById(id);

                ReleaseDate = Movie.RelaseDate;

                return Page();
            }
        }
        public IActionResult OnPostCancel()
        {
            HttpContext.Session.Remove("TempMovieId");
            return RedirectToPage("/Admin/Movies");
        }
        public IActionResult OnPostUpdate()
        {
            if (AdminPassword == "Admin1234!")
            {
                int? tempid = HttpContext.Session.GetInt32("TempMovieID");
                int id = tempid.HasValue ? tempid.Value : 0;

                _movie.UpdateMovie(id, Title, AgeRating, Hours, Miuntes, ReleaseDate, Price);

                if (Img != null && Img.Length > 0)
                {
                                        
                    string uniqueFileName = $"id{id}{Path.GetExtension(Img.FileName)}";
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pics", "Movies", uniqueFileName);

                    if (Movie.Img == filePath)
                    {
                        Directory.Delete(filePath);
                    }

                    using (var fileStream = new FileStream(filePath, FileMode.Create)) { Img.CopyTo(fileStream); }

                    string relativeFilePath = $"/pics/Movies/{uniqueFileName}";
                    _movie.UpdateMoviePicture(id, relativeFilePath);
                }

                HttpContext.Session.Remove("TempMovieID");
                return RedirectToPage("/Admin/Movies");
            }
            else
            {
                HttpContext.Session.Remove("TempMovieID");
                return RedirectToPage("/Admin/Movies");
            }
        }
    }
}

Flockbuster/Pages/Admin/Edit/user.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Flockbuster.Pages.Admin.Edit
{
    public class UserModel : PageModel
    {
        private readonly IUser _user;
        public UserModel(IUser user)
        {
            _user = user;
        }

        [BindProperty]
        public Users User { get; set; } = new Users();

        [BindProperty]
        public string UserFirstName { get; set; } = string.Empty;

        [BindProperty]
        public string UserLastName { get; set; } = string.Empty;

        [BindProperty]
        public string FirstName { get; set; } = string.Empty;

        [BindProperty]
        public string LastName { get; set; } = string.Empty;

        [BindProperty]
        public string EmailAddress { get; set; } = string.Empty;

        [BindProperty]
        public string Age { get; set; } = string.Empty;

        [BindProperty]
        [MinLength(8)]
        public string Password { get; set; } = string.Empty;

        [BindProperty]
        public string ConfirmPassword { get; set; } = string.Empty;
        [BindProperty]
        public string AdminPassword { get; set; } = string.Empty;
        [BindProperty]
        public bool IsChecked { get; set; }

        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                int? tempid = HttpContext.Session.GetInt32("TempUserId");
                int id = tempid.HasValue ? tempid.Value : 0;
                User = _user.GetUsersById(id);

                string[] names = User.Name.Split(' ');
                UserFirstName = names[0];
                UserLastName = names[1];

                return Page();
            }
        }

        public IActionResult OnPostCancel()
        {
            HttpContext.Session.Remove("TempUserId");
            return RedirectToPage("/Admin/Users");
        }
        public IActionResult OnPostUpdate()
        {
            int? tempid = HttpContext.Session.GetInt32("TempUserId");
            int id = tempid.HasValue ? tempid.Value : 0;
            string fullName = FirstName + " " + LastName;
            if (AdminPassword == "Admin1234!")
            {
                if (!string.IsNullOrEmpty(Password) && Password == ConfirmPassword) { _user.UpdateUserPassword(id, ConfirmPassword); }
                if (IsChecked) { _user.Admin(id, true); }
                else { _user.Admin(id, false); }
                _user.UpdateUser(id, fullName, Convert.ToInt32(Age), EmailAddress);
                HttpContext.Session.Remove("TempUserId");
                return RedirectToPage("/Admin/Users");
            }
            else { return RedirectToAction("adminInput"); }
        }
    }
}

Flockbuster/Pages/Admin/MovieHistory.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages.Admin
{
    public class MovieHistoryModel : PageModel
    {
        private readonly IMovie _movie;
        private readonly IUser _user;

        public MovieHistoryModel(IMovie movie, IUser user)
        {
            _movie = movie;
            _user = user;
        }
        [BindProperty]
        public List<BorrowedMovie> BorrowedMovies { get; set; } = new List<BorrowedMovie>();
        public IActionResult OnGet()
        {
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                BorrowedMovies = _movie.GetBorrowedMovies();

                foreach (BorrowedMovie borrowed in BorrowedMovies)
                {
                    borrowed.MovieName = _movie.GetMoviesById(borrowed.MovieID).Title;
                    borrowed.UserName = _user.GetUsersById(borrowed.UserID).Name;
                }

                return Page();
            }
        }
    }
}

Flockbuster/Pages/Admin/Movies.cshtml.cs
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Flockbuster.Domain.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Flockbuster.Service.Methods;

namespace Flockbuster.Pages.Admin
{
    public class MoviesModel : PageModel
    {
        private readonly IMovie _movie;
        public MoviesModel(IMovie movie) 
        { 
            _movie = movie;
        }
        [BindProperty]
        public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
        public IActionResult OnGet()
        {
            ListOfMovies = _movie.GetMovies();
            foreach (Movies mov in ListOfMovies)
            {
                List<Genre> genreForMovies = _movie.GetMovieGenre(mov.Id);
                mov.Genres = genreForMovies;
            }
            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPostEdit(int movieId)
        {
            HttpContext.Session.SetInt32("TempMovieID", movieId);
            return RedirectToPage("/Admin/Edit/Movie");
        }
        public IActionResult OnPostCreate()
        {
            return RedirectToPage("/Admin/Create/Movie");
        }
        public IActionResult OnPostDelete(int movieId)
        {
            _movie.DeleteMovie(movieId);
            return RedirectToPage("/Admin/Movies");
        }
    }
}

Flockbuster/Pages/Admin/Users.cshtml.cs
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Flockbuster.Domain.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Flockbuster.Service.Methods;

namespace Flockbuster.Pages.Admin
{
    public class UsersModel : PageModel
    {
        private readonly IUser _user;
        public UsersModel(IUser user)
        {
            _user = user;
        }
        [BindProperty]
        public List<Users> ListOfUsers { get; set; } = new List<Users>();
        public IActionResult OnGet()
        {
            ListOfUsers = _user.GetUsers();
            ListOfUsers.RemoveAt(0);

            if (!HttpContext.Session.GetInt32("ID").HasValue || !HttpContext.Session.GetBoolean("Admin"))
            {
                return RedirectToPage("/error/403");
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPostEdit(int userId)
        {
            HttpContext.Session.SetInt32("TempUserId", userId);
            return RedirectToPage("/Admin/Edit/User");
        }
        public IActionResult OnPostDelete(int userId)
        {
            _user.DeleteUser(userId);
            return RedirectToPage("/Admin/Users");
        }
    }
}

Flockbuster/Pages/User/Dashboard.cshtml.cs
using Flockbuster.Domain.Models;
using Flockbuster.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using static System.Reflection.Metadata.BlobBuilder;

namespace Flockbuster.Pages.User
{
    public class DashboardModel : PageModel
    {
		private readonly IUser _user;
		private readonly IMovie _movie;

		public DashboardModel(IUser user, IMovie movie)
		{
			_user = user;
			_movie = movie;
		}
		[BindProperty]
		public Users UserDetails { get; set; }
		[BindProperty]
		public List<Movies> ListOfMovies { get; set; } = new List<Movies>();
		[BindProperty]
		public int Balance { get; set; }
		public IActionResult OnGet()
		{
			if (!HttpContext.Session.GetInt32("ID").HasValue || HttpContext.Session.GetBoolean("Admin"))
			{
				return RedirectToPage("/error/403");
			}
			else
			{
				int? tempId = HttpContext.Session.GetInt32("ID");
				int id = tempId.HasValue ? tempId.Value : 0;
				UserDetails = _user.GetUsersById(id);

				BorrowedMovie loanedMovie = new BorrowedMovie();
				loanedMovie = _movie.GetBorrowedMovieById(id);

				Movies borrowedMovie = new Movies();
				borrowedMovie = _movie.GetMoviesById(loanedMovie.MovieID);
				borrowedMovie.ReturnDate = loanedMovie.ReturnDate;

				if (loanedMovie.Id != 0 && loanedMovie.IsBorrowed)
				{
					ListOfMovies.Add(borrowedMovie);
				}
				foreach (Movies mov in ListOfMovies)
				{
					List<Genre> genresForMovie = _movie.GetMovieGenre(loanedMovie.MovieID);
					mov.Genres = genresForMovie;
				}

				return Page();
			}
		}
		public IActionResult OnPostReturn(int movieId)
		{
            int? tempId = HttpContext.Session.GetInt32("ID");
            int id = tempId.HasValue ? tempId.Value : 0;
            _movie.ReturnMovie(movieId, id);
			return RedirectToPage("/User/Dashboard");
		}
		public IActionResult OnPostAddBalance()
		{
			int? tempId = HttpContext.Session.GetInt32("ID");
			int id = tempId.HasValue ? tempId.Value : 0;
			if (Balance > 0) 
			{
				_user.UpdateUserBalancePlus(id, Balance);
			}
			else
			{
                Console.WriteLine(Balance);
            }
			return RedirectToPage("/User/Dashboard");
		}
		public IActionResult OnPostWithdrawBalance()
		{
			int? tempId = HttpContext.Session.GetInt32("ID");
			int id = tempId.HasValue ? tempId.Value : 0;
			if (Balance > 0 && Balance <= _user.GetUsersById(id).Balance)
			{
				_user.UpdateUserBalanceMinus(id, Balance);
			}
			else
			{
				Console.WriteLine(Balance);
			}
			return RedirectToPage("/User/Dashboard");
		}
	}
}

Flockbuster/Pages/User/Movies.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flockbuster.Pages.User
{
    public class MoviesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Flockbuster/Pages/Admin/Dashboard.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.Admin.DashboardModel
@{
    ViewData["Title"] = "Admin - Dashboard";
}

<div class="container d-flex justify-content-between">
	<div class="card h-100 col-sm-3 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<h5 class="mb-2">Shortcuts</h5>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<a href="~/admin/Users">Site users </a>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<a href="~/admin/Movies">Mange movies </a>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<a href="~/admin/MovieHistory">Borrowed movies </a>
			</div>
		</div>
	</div>
	<div class="card h-100 w-50 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body">
			<div class="row gutters">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
					<h5 class="mb-4">Site information</h5>
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">Users:</h6>
					@Model.ListOfUsers.Count()
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">Movies:</h6>
					@Model.ListOfMovies.Count()
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">Borrowed Movies:</h6>
					@Model.ListOfBorrowedMovies.Count()
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<h6 class="mt-3">Genres:</h6>
					@Model.ListOfGenres.Count()
				</div>
			</div>
		</div>
	</div>
</div>

@*<div class="container">
	<div class="card h-75 w-100 shadow p-3 mb-5 bg-body-tertiary rounded">
		<div class="card-body">

		</div>
	</div>
</div>*@

Flockbuster/Pages/Admin/MovieHistory.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.Admin.MovieHistoryModel
@{
    ViewData["Title"] = "Admin - Movie History";
}

<div class="mt-2 container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Name of user</th>
                <th scope="col">Return Date</th>
                <th scope="col">Borrowed?</th>
            </tr>
        </thead>
        <tbody>
            @foreach (BorrowedMovie borrowed in Model.BorrowedMovies)
            {
                <tr>
                    <th scope="row">@borrowed.Id</th>
                    <td>@borrowed.MovieName</td>
                    <td>@borrowed.UserName</td>
                    <td>@borrowed.ReturnDate.ToShortDateString()</td>
                    @if (borrowed.IsBorrowed)
                    {
                        <td>Yes</td>
                    }
                    else
                    {
                        <td>Was borrowed</td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

Flockbuster/Pages/Admin/Movies.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.Admin.MoviesModel
@{
    ViewData["Title"] = "Admin - Movies";
}

<div class="container d-flex justify-content-end">
    <form method="post" class="d-flex">
        <button class="btn btn-outline-primary me-2" type="submit" asp-page-handler="Create"><i class="fa-solid fa-film">  Create</i></button>
    </form>
</div>
<div class="mt-2 container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Img</th>
                <th scope="col">Title</th>
                <th scope="col">Age Rating</th>
                <th scope="col">Time To Watch</th>
                <th scope="col">Release date</th>
                <th scope="col">Price</th>
                <th scope="col">Genres</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Movies mov in Model.ListOfMovies)
            {
                <tr>
                    <th scope="row">@mov.Id</th>
                    <td style="width:50px; height:50px;">
                        <img src="@mov.Img" style="max-height:100%; max-width:100%" />
                    </td>
                    <td>@mov.Title</td>
                    <td>@mov.RequiredAge</td>
                    <td>@(mov.TTW / 3600)h @((mov.TTW / 60) - (mov.TTW / 3600 * 60))m</td>
                    <td>@mov.RelaseDate.ToShortDateString()</td>
                    <td>@mov.Price DKK</td>
                    <td class="dropdown">
                        <a class="dropdown-toggle text-dark" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Genres
                        </a>
                        <ul class="dropdown-menu" data-bs-auto-close="false">
                            @foreach (Genre genre in mov.Genres)
                            {
                                <li><a class="dropdown-item">@genre.GenreName</a></li>
                            }
                        </ul>
                    </td>
                    <td class="d-flex justify-content-end">
                        <form method="post">
                            <button class="btn btn-outline-primary me-2" type="submit" asp-page-handler="Edit" asp-route-movieId="@mov.Id"><i class="fa-solid fa-pen"></i></button>
                        </form>
                        <button class="btn btn-outline-danger me-2" data-bs-toggle="modal" data-bs-target="#movDeleteModal-@mov.Id"><i class="fa-solid fa-trash-can"></i></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@foreach (Movies mov in Model.ListOfMovies)
{
    <div class="modal fade" id="movDeleteModal-@mov.Id" tabindex="-1" aria-labelledby="movDeleteModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-danger" id="movDeleteModal-@mov.Id">Delete</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        Title of Movie: @mov.Title
                    </div>
                    <div class="mb-3">
                        Age Rating: @mov.RequiredAge
                    </div>
                    <div class="mb-3">
                        Time To Watch: @mov.TTW
                    </div>
                    <div class="mb-3">
                        Release Date: @mov.RelaseDate
                    </div>
                    <div class="mb-3">
                        Price: @mov.Price
                    </div>
                    <div class="mt-3">
                        Are you sure you want to delete this movie?
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">No</button>
                    <form method="post">
                        <button type="submit" class="btn btn-danger" data-bs-dismiss="modal" asp-page-handler="Delete" asp-route-movieId="@mov.Id">Yes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

Flockbuster/Pages/Admin/Users.cshtml
@page
@using Flockbuster.Domain.Models;
@model Flockbuster.Pages.Admin.UsersModel
@{
    ViewData["Title"] = "Admin - Users";
}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">E-mail</th>
                <th scope="col">Age</th>
                <th scope="col">Balance</th>
                <th scope="col">Admin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Users user in Model.ListOfUsers)
            {
                <tr>
                    <th scope="row">@(user.Id - 1)</th>
                    <td>@user.Name</td>
                    <td>@user.Email</td>
                    <td>@user.Age</td>
                    <td>@user.Balance DKK</td>
                    <td>@user.IsAdmin</td>
                    <td class="d-flex justify-content-end">
                        <form method="post">
                            <button class="btn btn-outline-primary me-2" type="submit" asp-page-handler="Edit" asp-route-userId="@user.Id"><i class="fa-solid fa-pen"></i></button>
                        </form>
                        <button class="btn btn-outline-danger me-2" data-bs-toggle="modal" data-bs-target="#userDeleteModal-@user.Id"><i class="fa-solid fa-trash-can"></i></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@foreach (Users user in Model.ListOfUsers)
{
    <div class="modal fade" id="userDeleteModal-@user.Id" tabindex="-1" aria-labelledby="userDeleteModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-danger" id="userDeleteModal-@user.Id">Delete</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        Name: @user.Name
                    </div>
                    <div class="mb-3">
                        Email: @user.Email
                    </div>
                    <div class="mb-3">
                        Age: @user.Age
                    </div>
                    <div class="mb-3">
                        Balance: @user.Balance
                    </div>
                    <div class="mb-3">
                        Admin: @{
                            if (user.IsAdmin)
                            {
                                <p>Is admin</p>
                            }
                            else
                            {
                                <p>Not admin</p>
                            }
                        }
                    </div>
                    <div class="mb-3">
                        Are you sure you want to delete this user?
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">No</button>
                    <form method="post">
                        <button type="submit" class="btn btn-danger" data-bs-dismiss="modal" asp-page-handler="Delete" asp-route-userId="@user.Id">Yes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}